version: '3'
services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/app/
    ports:
      - 3002:3002
    depends_on:
      - modules-db
  modules-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: totally-secure-password
      POSTGRES_DB: learning-modules
    ports:
      - 5432:5432
    # volumes:
    #   - modules-db:/var/lib/mysql
volumes:
  modules-db: